import {
    IconBrandDiscord,
    IconBrandDocker,
    IconBrandFigma,
    IconBrandGithub,
    IconBrandGitlab,
    IconBrandGmail,
    IconBrandMedium,
    IconBrandNotion,
    IconBrandSkype,
    IconBrandSlack,
    IconBrandStripe,
    IconBrandTelegram,
    IconBrandTrello,
    IconBrandWhatsapp,
    IconBrandZoom,
  } from '@tabler/icons-react'
  
  export const apps = [
    {
      name: 'Telegram',
      logo: <IconBrandTelegram />,
      type: "client",
      desc: 'Connect with Telegram for real-time communication.',
    },
    {
      name: 'Notion',
      logo: <IconBrandNotion />,
      type: "internal",
      desc: 'Effortlessly sync Notion pages for seamless collaboration.',
    },
    {
      name: 'Figma',
      logo: <IconBrandFigma />,
      type: "internal",
      desc: 'View and collaborate on Figma designs in one place.',
    },
    {
      name: 'Trello',
      logo: <IconBrandTrello />,
      type: "client",
      desc: 'Sync Trello cards for streamlined project management.',
    },
    {
      name: 'Slack',
      logo: <IconBrandSlack />,
      type: "client",
      desc: 'Integrate Slack for efficient team communication',
    },
    {
      name: 'Zoom',
      logo: <IconBrandZoom />,
      type: "internal",
      desc: 'Host Zoom meetings directly from the dashboard.',
    },
    {
      name: 'Stripe',
      logo: <IconBrandStripe />,
      type: "client",
      desc: 'Easily manage Stripe transactions and payments.',
    },
    {
      name: 'Gmail',
      logo: <IconBrandGmail />,
      type: "internal",
      desc: 'Access and manage Gmail messages effortlessly.',
    },
    {
      name: 'Medium',
      logo: <IconBrandMedium />,
      type: "client",
      desc: 'Explore and share Medium stories on your dashboard.',
    },
    {
      name: 'Skype',
      logo: <IconBrandSkype />,
      type: "client",
      desc: 'Connect with Skype contacts seamlessly.',
    },
    {
      name: 'Docker',
      logo: <IconBrandDocker />,
      type: "client",
      desc: 'Effortlessly manage Docker containers on your dashboard.',
    },
    {
      name: 'GitHub',
      logo: <IconBrandGithub />,
      type: "client",
      desc: 'Streamline code management with GitHub integration.',
    },
    {
      name: 'GitLab',
      logo: <IconBrandGitlab />,
      type: "client",
      desc: 'Efficiently manage code projects with GitLab integration.',
    },
    {
      name: 'Discord',
      logo: <IconBrandDiscord />,
      type: "client",
      desc: 'Connect with Discord for seamless team communication.',
    },
    {
      name: 'WhatsApp',
      logo: <IconBrandWhatsapp />,
      type: "client",
      desc: 'Easily integrate WhatsApp for direct messaging.',
    },
  ]
  